#!/usr/bin/perl -w
use strict;

my $nonlexMax = shift;
my $lexicalMax = shift;

sub token_count {
  my $_ = shift;
  (() = m/ /g) + 1;
}

while (<>) {
  my (undef, $src, $tgt, undef) = split /\t/, $_, 4;
  my $lexical = ($src !~ /,1\]/);
  if ($lexical) {
    print if
      (token_count($src) <= $lexicalMax and token_count($tgt) <= $lexicalMax);
  } else {
    print if (token_count($src) <= $nonlexMax);
  }
}
