#!/usr/bin/perl -w
use strict;

my $nonlexMax = shift;
my $lexicalMax = shift;

sub token_count {
  my $_ = shift;
  split;
}

while (<>) {
  my (undef, $src, $tgt) = split /\t/;
  my $lexical = ($src !~ /,1\]/);
  if ($lexical) {
    print if
      (token_count($src) <= $lexicalMax and token_count($tgt) <= $lexicalMax);
  } else {
    print if (token_count($src) <= $nonlexMax);
  }
}
