#!/usr/bin/perl -w
use strict;

sub has_terminals {
  my $rhs = shift;
  grep { !/,\d+\]$/ } (split " ", $rhs);
}

while (<>) {
  my (undef,$src,$tgt) = split /\t/;
  print if (has_terminals($src) or has_terminals($tgt));
}
