#!/usr/bin/perl -w
use strict;

while (<>) {
  chomp;
  my @fields = split /\t/;
  $fields[5] =~ s/[^ 0-9=]+=//g;
  $fields[6] =~ s/[^ 0-9=]+=//g;
  print "$fields[0] ||| $fields[1] ||| $fields[2] ||| $fields[5] $fields[6]\n";
}
